#!/usr/bin/env bash

mapfile -d " " -t battery < <(acpi | sed 's/Bat.*:\ //g; s/,//g')

CAPACITY="<i>${battery[1]}</i>"

case ${battery[0]} in
    'Charging') STATE="<b><span color='$(xgetres color3)'>++</span></b>";;
    'Discharging') STATE="<b><span color='$(xgetres color1)'>--</span></b>";;
    'Full') STATE="<b><span color='$(xgetres color2)'>==</span></b>"
esac

if [[ -n ${battery[3]} ]]; then
    TIME=" <i><span color='$(xgetres color8)'>${battery[2]}</span></i>"
else
    TIME=""
fi


echo "${STATE}${CAPACITY}${TIME}"
