#!/bin/bash

case $1 in
    'updates')
                sudo pacman -Sy
                updates=$(sudo pacman -Qu | wc -l)
                if [[ $updates -gt 0 ]]; then
                    dunstify -u normal "Packages" \
                    "<span weight='bold'>$updates</span> outdated packages!"
                fi
    	        ;;

    'volume')
    	        volume=$(pulsemixer --get-volume | awk '{ print $1 }')
    	        color_volume=$(xgetres color10)
    	        [[ $volume -gt 100 ]] && color_volume=$(xgetres color9)

    	        play /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga \
                && \
    	        dunstify -u low -r 298745 "Volume $volume%" \
                "$(progressbar 30 "█" "<span color='$color_volume'>" \
                "<span color='$(xgetres color0)'>" $volume 150)"
    	        ;;

    'notes')
                notes=$(cat ~/notes | wc -l)
                dunstify "Notes" \
                "You have <span weight='bold' color='$(xgetres color5)'>$notes</span> notes in ~/notes"
                ;;

esac
